//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 06:34:20 PM MSK 
//


package com.fronya.candies;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import com.fronya.ingredient.Ingredient;


/**
 * <p>Java class for Candy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Candy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="type" type="{http://www.fronya.com/Candies}Type"/>
 *         &lt;element name="ingredient" type="{http://www.fronya.com/Ingredient}Ingredient"/>
 *         &lt;element name="nutritionValue" type="{http://www.fronya.com/Candies}NutritionValue"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Candy", propOrder = {
    "name",
    "energy",
    "type",
    "ingredient",
    "nutritionValue"
})
public class Candy {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BigInteger energy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Type type;
    @XmlElement(required = true)
    protected Ingredient ingredient;
    @XmlElement(required = true)
    protected NutritionValue nutritionValue;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the energy property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEnergy() {
        return energy;
    }

    /**
     * Sets the value of the energy property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEnergy(BigInteger value) {
        this.energy = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Type }
     *     
     */
    public Type getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Type }
     *     
     */
    public void setType(Type value) {
        this.type = value;
    }

    /**
     * Gets the value of the ingredient property.
     * 
     * @return
     *     possible object is
     *     {@link Ingredient }
     *     
     */
    public Ingredient getIngredient() {
        return ingredient;
    }

    /**
     * Sets the value of the ingredient property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ingredient }
     *     
     */
    public void setIngredient(Ingredient value) {
        this.ingredient = value;
    }

    /**
     * Gets the value of the nutritionValue property.
     * 
     * @return
     *     possible object is
     *     {@link NutritionValue }
     *     
     */
    public NutritionValue getNutritionValue() {
        return nutritionValue;
    }

    /**
     * Sets the value of the nutritionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link NutritionValue }
     *     
     */
    public void setNutritionValue(NutritionValue value) {
        this.nutritionValue = value;
    }

    @Override
    public String toString() {
        String ingredientString;
        if(type == Type.CHOCOLATE){
            ingredientString = ingredient.toStringChocolate();
        }else{
            ingredientString = ingredient.toString();
        }

        return "Candy " +
                "name= " + name + ' ' +
                ", energy=" + energy +
                ", type=" + type + '\n' +
                 ingredientString + '\n' +
                  nutritionValue + '\n';
    }
}
