//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.30 at 06:34:20 PM MSK 
//


package com.fronya.candies;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NutritionValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NutritionValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="protein" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="fat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="carbohydrate" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NutritionValue", propOrder = {
    "protein",
    "fat",
    "carbohydrate"
})
public class NutritionValue {

    protected float protein;
    protected float fat;
    protected float carbohydrate;

    /**
     * Gets the value of the protein property.
     * 
     */
    public float getProtein() {
        return protein;
    }

    /**
     * Sets the value of the protein property.
     * 
     */
    public void setProtein(float value) {
        this.protein = value;
    }

    /**
     * Gets the value of the fat property.
     * 
     */
    public float getFat() {
        return fat;
    }

    /**
     * Sets the value of the fat property.
     * 
     */
    public void setFat(float value) {
        this.fat = value;
    }

    /**
     * Gets the value of the carbohydrate property.
     * 
     */
    public float getCarbohydrate() {
        return carbohydrate;
    }

    /**
     * Sets the value of the carbohydrate property.
     * 
     */
    public void setCarbohydrate(float value) {
        this.carbohydrate = value;
    }

    @Override
    public String toString() {
        return "NutritionValue " +
                "protein=" + protein +
                ", fat=" + fat +
                ", carbohydrate=" + carbohydrate +
                '\n';
    }
}
